---
title: "SocCultExam"
output: word_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading all the experiment csv files
temp = list.files(pattern="*.csv")
for (i in 1:length(temp)) assign(temp[i], read.csv(temp[i]))

library(data.table)
#merge
# Get a List of all files in directory named with a key word, say all `.csv` files
filenames <- list.files("C:/Users/nikol/OneDrive - Aarhus universitet/AU Uni work/4. semester/social and cultural dynamics/exam/SocCultExam/data", pattern="*.csv", full.names=TRUE)

# read and row bind all data sets
data <- rbindlist(lapply(filenames,fread))


```


```{r}
# loading questionaire data
questions <- read.csv("C:/Users/nikol/OneDrive - Aarhus universitet/AU Uni work/4. semester/social and cultural dynamics/exam/SocCultExam/Investment-questionnaire.csv", sep=";")



# renaming 
colnames(questions) <- c("Tidsstempel", "Participant", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22")



# changing/reversing the scores because of negative/postive framing of the questions. 
questions[,c("2","4","5", "8", "9", "12", "13", "15", "16", "19", "20")]=7-questions[,c("2","4","5", "8", "9", "12", "13", "15", "16", "19", "20")]

# summing for the total score. 
questions$total = rowSums(questions[,3:24])

library(dplyr)

#renaming participant coloumn to ID to fit with the other dataframe
questions=plyr::rename(questions, c("Participant"="ID"))

```


```{r}
# extracting total coloumn
sub = select(questions, "ID", "total")


#merge all data - total score into the experiment data
compdata = merge(data, sub, by="ID")

compdata =as.data.frame(compdata)

```


```{r}

library(pastecs)
library(Metrics)
library(modelr)
library(ggplot2)
library(crqa)
library(readr)
library(lmerTest)
library(lme4)
library(rethinking)
library(plyr)
library(brms)
library(rstan)
library(devtools)


```


```{r}
# creating a coloumn with authority measure
compdata$authority[compdata$BOT =="A"]<-"1"
compdata$authority[compdata$BOT =="B"]<-"1"
compdata$authority[compdata$BOT =="C"]<-"0"
compdata$authority[compdata$BOT =="D"]<-"0"

# creating coloumn with reliability measure
compdata$reliability[compdata$BOT =="A"]<-"1"
compdata$reliability[compdata$BOT =="B"]<-"0"
compdata$reliability[compdata$BOT =="C"]<-"0"
compdata$reliability[compdata$BOT =="D"]<-"1"

compdata$authority = as.numeric(as.factor(compdata$authority))-1
compdata$reliability = as.numeric(as.factor(compdata$reliability))-1
```

```{r}
#scaling V1

compdata$V1.c = compdata$V1-mean(compdata$V1)

compdata$total.c = compdata$total-mean(compdata$total)


```

```{r}

# PR as numeric, then factor, subtracting 1 to make the variable 0's and 1's.
compdata$PR = as.numeric(as.factor(compdata$PR))-1

#making V1(trial) numeric
compdata$V1 = as.numeric(as.factor(compdata$V1))-1

```

# Analysis

```{r}
m1 = brm(PR~1, family = bernoulli(link = "logit"), compdata, chains=2, cores=2)
summary(m1)
```

```{r}
m2 = brm(PR~1+ authority, family = bernoulli(link = "logit"), compdata, chains=2, cores=2)
summary(m2)
```

```{r}
m3 = brm(PR~1+authority*total+(1|ID), family = bernoulli(link = "logit"), compdata, chains=2, cores=2)
summary(m3)
```


```{r}
#plotting m3
pairs(m3)

plot(m3)

```

```{r}
#riccardos model
m4 = brm(PR~1+authority+reliability+V1.c+(1+authority+reliability+V1.c|ID), family=bernoulli(link = "logit"), compdata, chains=2, cores=2)

summary(m4)

plot(m4)
```

```{r}

m5 = brm(PR~1+authority*V1.c*reliability+(1+authority+reliability+V1.c|ID), family=bernoulli(link = "logit"), compdata, chains=2, cores=2)

summary(m5)

plot(m5)
```

```{r}
m6 = brm(PR~1+authority*total.c*reliability+(1+authority+reliability+V1.c|ID), family=bernoulli(link = "logit"), compdata, chains=2, cores=2)

summary(m6)

plot(m6)
```

```{r}

post <- posterior_samples( m3)
authority.seq <- seq( from=0 , to=1 , by=1 )

sim.PR = sim(m3, data =list(authority = authority.seq))
PR.PI = apply(sim.PR,2,PI, prob =0.89)



```

```{r}

m2 <- add_ic(m2, ic="waic")
m3 <- add_ic(m3, ic="waic")
m4 <- add_ic(m4, ic="waic")
m5 <- add_ic(m5, ic="waic")
m6 <- add_ic(m6, ic="waic")

compare_ic(m2,m3,m4,m5,m6, ic="waic")

model_weights(m2, m3, m4, m5, m6, ic="waic")






```


```{r}

```



```{r}
compdata$reliabilityf=as.factor(compdata$reliability)
compdata$authorityf=as.factor(compdata$authority)



plot(marginal_effects(m5))
```

```{r}
plot(marginal_effects(m6))
```


```{r}
#dens plot simulated data from model on raw data
sim.m5 = sim(m5, data = compdata, n=1e4)
dens(sim.m5, col = "red", xlim = c(-1,2), ylim = c(0,5),  xlab = "PR")
par(new=TRUE)
dens(compdata$PR, xlim = c(-1, 2), ylim = c(0,5), xlab = "PR")
title("Model 5")
```


```{r}

```




















